# Generated by Django 4.2.2 on 2023-06-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_form_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='dob',
            field=models.DateField(),
        ),
    ]
