# Generated by Django 4.2.2 on 2023-06-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_form_app', '0004_alter_basicdetails_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationdetail',
            name='board_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='course_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='passing_year',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
