# Generated by Django 4.2.2 on 2023-06-07 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_form_app', '0005_educationdetail_board_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='email',
            field=models.EmailField(max_length=90),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_form_app.statemaster'),
        ),
    ]
