# Generated by Django 4.2.2 on 2023-06-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_form_app', '0006_alter_basicdetails_email_alter_basicdetails_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
