# Generated by Django 4.2.2 on 2023-06-07 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_form_app', '0007_alter_basicdetails_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job_form_app.statemaster'),
        ),
    ]
