# Generated by Django 4.2.2 on 2023-06-08 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_form_app', '0010_alter_educationdetail_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetail',
            name='student_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='job_form_app.basicdetails'),
        ),
    ]
