# Generated by Django 4.2.2 on 2023-06-08 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_form_app', '0013_alter_educationdetail_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_name', models.CharField(max_length=50)),
                ('select_key', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='educationdetail',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_form_app.basicdetails'),
        ),
        migrations.CreateModel(
            name='OptionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_value', models.CharField(max_length=100)),
                ('selectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_form_app.selectmaster')),
            ],
        ),
    ]
