# Generated by Django 4.2.2 on 2023-06-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_form_app', '0015_alter_educationdetail_course_name_workexperiences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='read_status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='languages',
            name='speak_status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='languages',
            name='write_status',
            field=models.BooleanField(),
        ),
    ]
