# Generated by Django 4.2.2 on 2023-06-09 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_form_app', '0016_alter_languages_read_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='languages',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_form_app.languagemaster'),
        ),
    ]
