# Generated by Django 4.2.2 on 2023-06-09 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_form_app', '0017_languagemaster_alter_languages_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techName', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='technologies',
            name='tech_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_form_app.technologymaster'),
        ),
    ]
