# Generated by Django 4.2.2 on 2023-06-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_form_app', '0018_technologymaster_alter_technologies_tech_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
