# Generated by Django 4.2.2 on 2023-06-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_form_app', '0019_alter_languages_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologies',
            name='tech_name',
            field=models.CharField(max_length=100),
        ),
    ]
