# Generated by Django 4.2.2 on 2023-06-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_form_app', '0020_alter_technologies_tech_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperiences',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workexperiences',
            name='start_date',
            field=models.DateField(),
        ),
    ]
