# Generated by Django 4.2.2 on 2023-06-10 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_form_app', '0021_alter_workexperiences_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicdetails',
            old_name='designation',
            new_name='designation1',
        ),
    ]
